version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"  # for Java Maven project
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    allow:
      - dependency-type: "direct"
    reviewers:
      - "vchaudh3"
