name: Java CI Reusable Workflow

on:
  workflow_call:
    inputs:
      java-version:
        required: false
        type: string
        default: '17'
      distribution:
        required: false
        type: string
        default: 'temurin'
    secrets:
      SONAR_TOKEN:
        required: true
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true

jobs:
  build-java-app:
    runs-on: ubuntu-latest
    name: Assignment 1-3:Build, Test, Sonar Scan, Docker Push

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ inputs.java-version }}
          distribution: ${{ inputs.distribution }}

      - name: Assignment-1:Build with Maven
        run: mvn clean package --no-transfer-progress

      - name: Assignment-2:SonarCloud Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=vchaudh3_sonar-2607-2127 | tee sonar_output.log

      - name: Assignment-2:Upload Sonar Report Log as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: sonar-scan-log
          path: sonar_output.log

      - name: Assignment-3:Build Docker Image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/vulnado:${{ github.sha }} .

      - name: Assignment-3:Push Docker Image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/vulnado:${{ github.sha }}
